// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0a6uriVv4EHDirMJs4Hp25RX8py3jQ4w',
    appId: '1:655433559329:android:546d5f8ce802e5ac116260',
    messagingSenderId: '655433559329',
    projectId: 'assistenciaos',
    storageBucket: 'assistenciaos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkGdnM_StgUee9FzaqUuwgmwHIt_Fr1aE',
    appId: '1:655433559329:ios:2deffd19582c73b9116260',
    messagingSenderId: '655433559329',
    projectId: 'assistenciaos',
    storageBucket: 'assistenciaos.firebasestorage.app',
    iosBundleId: 'com.mr.dev.assistencia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7F_gWpeo4EuPrRxue_hQ0Hkq1_IP3TcI',
    appId: '1:655433559329:web:2b62574fa2447b10116260',
    messagingSenderId: '655433559329',
    projectId: 'assistenciaos',
    authDomain: 'assistenciaos.firebaseapp.com',
    storageBucket: 'assistenciaos.firebasestorage.app',
    measurementId: 'G-LV1FYZZ08Y',
  );
}